In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/pulkith/Desktop/Development/Ryktor/backend/app/services/projectdata/Hospitals.csv')

In [3]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'ID', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP',
       'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD'],
      dtype='object')

In [6]:
dft = df[['NAME','ID','STATUS','POPULATION','NAICS_CODE','NAICS_DESC','VAL_METHOD','WEBSITE','STATE_ID','OWNER','TTL_STAFF','BEDS','TRAUMA','HELIPAD']]
dft

,NAME,ID,STATUS,POPULATION,NAICS_CODE,NAICS_DESC,VAL_METHOD,WEBSITE,STATE_ID,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,ANDALUSIA HEALTH,1336420,OPEN,88,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,http://www.andalusiaregionalhospital.com,H2001,PROPRIETARY,-999,88,LEVEL III,Y
1,ATHENS LIMESTONE HOSPITAL,1535611,OPEN,71,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,http://www.athenslimestonehospital.com,H4201,PROPRIETARY,-999,71,LEVEL III,N
2,ATMORE COMMUNITY HOSPITAL,136502,OPEN,51,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,http://www.ebaptisthealthcare.org/atmorecommun...,H2704,NON-PROFIT,-999,51,LEVEL III,Y
3,BAPTIST MEDICAL CENTER EAST,236124,OPEN,150,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,http://www.baptistfirst.org,H5107,GOVERNMENT - DISTRICT/AUTHORITY,-999,150,NOT AVAILABLE,Y
4,BAPTIST MEDICAL CENTER SOUTH,1736111,OPEN,432,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,http://www.baptistfirst.org,H5102,GOVERNMENT - DISTRICT/AUTHORITY,-999,432,LEVEL II,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8335,REHABILITATION HOSPITAL OF NAPLES,196785202,OPEN,50,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,www.encompasshealth.com/locations/naplesrehab,458386,PROPRIETARY,-999,50,NOT AVAILABLE,N
8336,SINAI-GRACE HOSPITAL,196785128,OPEN,383,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,NOT AVAILABLE,1060000012,NOT AVAILABLE,-999,383,NOT AVAILABLE,Y
8337,ASCENSION ST JOHN HOSPITAL,196785137,OPEN,654,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,NOT AVAILABLE,1060000072,NOT AVAILABLE,-999,654,NOT AVAILABLE,Y
8338,US AIR FORCE HOSPITAL-GLENDALE,196785364,OPEN,-999,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,UNVERIFIED,NOT AVAILABLE,MED3078,NOT AVAILABLE,-999,-999,NOT AVAILABLE,N
8339,KAISER FOUNDATION HOSPITAL - SAN MARCOS,196785281,OPEN,168,622110,GENERAL MEDICAL AND SURGICAL HOSPITALS,IMAGERY/OTHER,NOT AVAILABLE,630027120,NON-PROFIT,-999,168,NOT AVAILABLE,N

In [12]:
dft['TRAUMA'].value_counts()

TRAUMA
NOT AVAILABLE                                    5983
LEVEL IV                                         1004
LEVEL III                                         537
LEVEL II                                          326
LEVEL I                                           234
TRH                                                38
TRF                                                32
CTH                                                28
LEVEL I PEDIATRIC                                  27
LEVEL V                                            18
LEVEL I ADULT, LEVEL I PEDIATRIC                   17
LEVEL I ADULT, LEVEL II PEDIATRIC                  17
Level II Trauma Center                             16
LEVEL II ADULT, LEVEL II PEDIATRIC                 10
ATH                                                 8
LEVEL III ADULT                                     7
LEVEL II PEDIATRIC                                  7
RTC                                                 5
LEVEL I ADULT                                       5
PEDIATRIC                                           3
Level I Trauma Center                               2
LEVEL II ADULT                                      2
LEVEL II, LEVEL II PEDIATRIC                        2
LEVEL II / PEDIATRIC                                2
LEVEL I, LEVEL II PEDIATRIC                         2
LEVEL II REHAB                                      1
Level III                                           1
LEVEL II, LEVEL III PEDIATRIC, LEVEL II REHAB       1
PARC                                                1
LEVEL I PEDIATRIC REHAB                             1
RTH                                                 1
REGIONAL                                            1
LEVEL I, LEVEL I PEDIATRIC                          1
Name: count, dtype: int64

In [4]:
# replaces all values of -999 with 0 for all columns
dft = dft.replace(-999, 0)
score = 1.0
population_mean = dft['POPULATION'].mean()
pop_score = -(dft["POPULATION"].std() - population_mean) / 5
naics_score = 0.0

if

Index(['X', 'Y', 'OBJECTID', 'ID', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP',
       'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD'],
      dtype='object')