In [1]:
import pandas as pd

In [7]:
df = pd.read_excel('/Users/pulkith/Desktop/Development/Ryktor/backend/app/eda/ZIP5_OCT2024_v0820.xlsx')

In [8]:
df

,STATE,ZIP CODE,CARRIER,LOCALITY,RURAL IND,LAB CB LOCALITY,RURAL IND2,PLUS 4 FLAG,PART B DRUG INDICATOR,YEAR/QTR
0,AK,99501.0,2102.0,1.0,NaN,Z9,NaN,0.0,A,20244.0
1,AK,99502.0,2102.0,1.0,NaN,Z9,NaN,0.0,A,20244.0
2,AK,99503.0,2102.0,1.0,NaN,Z9,NaN,0.0,A,20244.0
3,AK,99504.0,2102.0,1.0,NaN,Z9,NaN,0.0,A,20244.0
4,AK,99505.0,2102.0,1.0,NaN,Z9,NaN,0.0,A,20244.0
...,...,...,...,...,...,...,...,...,...,...
42942,WY,83126.0,3602.0,21.0,B,Z9,B,0.0,A,20244.0
42943,WY,83127.0,3602.0,21.0,B,Z9,B,0.0,A,20244.0
42944,WY,83128.0,3602.0,21.0,B,Z9,B,0.0,A,20244.0
42945,WY,83414.0,3602.0,21.0,B,Z9,B,0.0,A,20244.0
42946,_x001A_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN